import type {
  FramingInterpretation,
  OpeningInterpretation,
  WallInterpretation,
} from './types'
import type {
  Door,
  FramingSettings,
  Opening,
  Project,
  Wall,
  Window,
} from '../../types/project'
import { getDefaultMaterialPrices } from '../../data/defaultPrices'
import { calculateFramingEstimate } from '../framingCalculator'
import { validateFramingInterpretation } from './framingValidator'

/**
 * Bridges a validated FramingInterpretation into a canonical FrameCalcPro Project object,
 * calculating material takeoffs and configuring 3D BIM parameters.
 */
export function convertInterpretationToProject(
  interpretation: FramingInterpretation,
  projectName?: string
): { project: Project; estimate: ReturnType<typeof calculateFramingEstimate> } {
  const now = new Date().toISOString()
  const projectId = `proj-ai-${Date.now()}`

  const { building, roof, walls: interpWalls, openings: interpOpenings, scale } = interpretation

  // Map walls
  const walls: Wall[] = interpWalls.map((w) => ({
    id: w.id,
    name: w.name || `${w.side.toUpperCase()} Wall`,
    length: w.length,
    height: w.height,
  }))

  // Map openings
  const openings: Opening[] = interpOpenings.map((op) => {
    const isDoor = op.type === 'door' || op.type === 'slider' || op.type === 'garage'
    if (isDoor) {
      const door: Door = {
        id: op.id,
        type: 'door',
        name: op.name,
        wallId: op.wallId,
        width: op.width,
        height: op.height,
        quantity: 1,
        headerSize: op.headerSize,
      }
      return door
    }
    const win: Window = {
      id: op.id,
      type: 'window',
      name: op.name,
      wallId: op.wallId,
      width: op.width,
      height: op.height,
      quantity: 1,
      headerSize: op.headerSize,
    }
    return win
  })

  // Determine framing settings from interpretation
  const primaryWall = interpWalls[0]
  const spacingVal = primaryWall?.studSpacing ?? 16
  const spacingOption = ([12, 16, 24].includes(spacingVal)
    ? String(spacingVal)
    : '16') as FramingSettings['studSpacing']

  const settings: FramingSettings = {
    studSpacing: spacingOption,
    customStudSpacing: spacingVal,
    wallThickness: primaryWall?.studSize ?? '2x6',
    customWallThickness: primaryWall?.studSize === '2x6' ? 5.5 : 3.5,
    topPlate: primaryWall?.topPlate ?? 'double',
    wastePercent: 10,
    includeSheathing: true,
    sheathingType: 'osb',
    boardLength: 16,
    cornerType: 'california',
    blockingType: 'mid-height',
  }

  const notesText = [
    `Generated by FrameCalcPro AI Image → 3D Framing Generator`,
    `Reference File: ${interpretation.imageFileName || 'Uploaded Image'}`,
    `Scale Reference: ${scale.label} (Confidence: ${scale.confidence.toUpperCase()})`,
    `Building Silhouette: ${building.overallWidth} ft × ${building.overallDepth} ft (${building.stories} ${building.stories === 1 ? 'Story' : 'Stories'})`,
    `Roof Framing: ${roof.type.toUpperCase()} • Pitch: ${roof.pitch} • Overhang: ${roof.overhangInches}"`,
    `Framing Rules: ${interpretation.framingRulesApplied.join('; ')}`,
  ].join('\n')

  const project: Project = {
    id: projectId,
    name: projectName || `AI Framing: ${interpretation.imageFileName.replace(/\.[^/.]+$/, '') || 'House Model'}`,
    projectType: interpretation.projectType || 'residential',
    propertyConfig: building.stories === 2 ? { numUnits: 2 } : undefined,
    measurementSystem: building.units,
    walls,
    openings,
    settings,
    materialPrices: getDefaultMaterialPrices(),
    customTakeoffLines: [],
    notes: notesText,
    createdAt: now,
    updatedAt: now,
  }

  const estimate = calculateFramingEstimate(project)

  return { project, estimate }
}

export interface ParameterUpdates {
  overallWidth?: number
  overallDepth?: number
  stories?: 1 | 2
  floorHeight?: number
  studSize?: '2x4' | '2x6'
  studSpacing?: 12 | 16 | 24
  roofType?: 'gable' | 'hip' | 'shed' | 'gambrel'
  roofPitch?: '4/12' | '5/12' | '6/12' | '7/12' | '8/12' | '10/12' | '12/12' | '14/12'
  roofOverhangInches?: number
}

/**
 * Regenerates the FramingInterpretation after user adjusts building or structural parameters.
 * Re-computes perimeter walls, repositioned openings, roof geometry, and validation.
 */
export function updateInterpretationParameters(
  current: FramingInterpretation,
  updates: ParameterUpdates
): FramingInterpretation {
  const newWidth = updates.overallWidth ?? current.building.overallWidth
  const newDepth = updates.overallDepth ?? current.building.overallDepth
  const newStories = updates.stories ?? current.building.stories
  const newFloorHeight = updates.floorHeight ?? current.building.floorHeight
  const newStudSize = updates.studSize ?? current.walls[0]?.studSize ?? '2x6'
  const newStudSpacing = updates.studSpacing ?? current.walls[0]?.studSpacing ?? 16
  const newRoofType = updates.roofType ?? current.roof.type
  const newRoofPitch = updates.roofPitch ?? current.roof.pitch
  const newRoofOverhang = updates.roofOverhangInches ?? current.roof.overhangInches

  const pitchRatio = parseInt(newRoofPitch, 10) / 12
  const roofHeight = Math.round((newWidth / 2) * pitchRatio)
  const overallHeight = newStories * newFloorHeight + roofHeight

  // Update perimeter walls
  const updatedWalls: WallInterpretation[] = current.walls.map((w) => {
    const isWidthWall = w.side === 'front' || w.side === 'back'
    return {
      ...w,
      length: isWidthWall ? newWidth : newDepth,
      height: newFloorHeight,
      studSize: newStudSize,
      studSpacing: newStudSpacing,
      source: 'USER-CONFIRMED',
    }
  })

  // Re-bound openings if wall lengths changed
  const updatedOpenings: OpeningInterpretation[] = current.openings.map((op) => {
    const parentWall = updatedWalls.find((w) => w.id === op.wallId)
    if (!parentWall) return op

    // Center or shift if outside new length
    let newX = op.x
    if (newX + op.width > parentWall.length - 0.5) {
      newX = Math.max(1, parentWall.length - op.width - 1)
    }

    return {
      ...op,
      x: Math.round(newX * 10) / 10,
      source: 'USER-CONFIRMED',
    }
  })

  const updated: FramingInterpretation = {
    ...current,
    timestamp: new Date().toISOString(),
    building: {
      ...current.building,
      overallWidth: newWidth,
      overallDepth: newDepth,
      stories: newStories,
      floorHeight: newFloorHeight,
      overallHeight,
      source: 'USER-CONFIRMED',
    },
    roof: {
      ...current.roof,
      type: newRoofType,
      pitch: newRoofPitch,
      pitchRatio,
      overhangInches: newRoofOverhang,
      ridgeLengthFt: newDepth,
      source: 'USER-CONFIRMED',
    },
    walls: updatedWalls,
    openings: updatedOpenings,
    validation: { valid: true, errors: [], warnings: [] },
  }

  updated.validation = validateFramingInterpretation(updated)
  return updated
}
